name: Builds and pushes the container image

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  REGISTRY: ghcr.io

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Put current date into a variable
        run: echo "NOW=$(date)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup QEMU for multiplatform support
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
          labels: |
            maintainer=thomas.herzog@ihet.at
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.title=AWS EC2 Provisioner
            org.opencontainers.image.description=Provisions an EC2 environment based on a provided configuration
            org.opencontainers.image.vendor=Thomas Herzog
            org.opencontainers.image.version=${{ github.ref_name }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ env.NOW }}
            org.opencontainers.image.licenses=GPL-3.0
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          file: Containerfile
          context: ./
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
